# Generated by Django 4.0.3 on 2022-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupform',
            name='Confirmpass',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='id',
        ),
        migrations.AlterField(
            model_name='signupform',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
