# Generated by Django 4.0.3 on 2022-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0002_remove_signupform_confirmpass_remove_signupform_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBookForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=60)),
                ('serial_number', models.IntegerField()),
            ],
        ),
    ]
