# Generated by Django 4.0.3 on 2022-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0003_addbookform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('title', models.CharField(max_length=90)),
                ('Author', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AddBookForm',
        ),
    ]
