# Generated by Django 4.0.5 on 2022-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0005_addbook_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('story', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
