# Generated by Django 4.0.5 on 2022-09-13 18:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0007_alter_new_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='story',
            field=django_quill.fields.QuillField(),
        ),
    ]
