# Generated by Django 4.0.5 on 2022-09-14 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0009_alter_new_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
