# Generated by Django 4.0.5 on 2022-09-14 13:56

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0011_alter_new_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='story',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
