# Generated by Django 4.0.5 on 2022-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0012_alter_new_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupForm',
        ),
    ]
