# Generated by Django 4.0.5 on 2022-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0015_addbook_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='Cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/%y'),
        ),
    ]
