# Generated by Django 4.0.5 on 2022-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0018_addbook_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='genre',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Economics', 'Economics'), ('Novel', 'Novel'), ('Science', 'Science'), ('Business', 'Business'), ('Mathematics', 'Mathematics')], default='Engineering', max_length=50),
        ),
    ]
