# Generated by Django 4.0.5 on 2023-02-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0026_issuebook_expirydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='expirydate',
            new_name='due_date',
        ),
    ]
