# Generated by Django 4.0.5 on 2023-02-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0027_rename_expirydate_issuebook_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Over Due', 'Over Due')], default='active', max_length=20),
        ),
    ]
