# Generated by Django 4.0.5 on 2023-02-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0029_addbook_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serial_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.addbook'),
        ),
    ]
