# Generated by Django 4.0.5 on 2023-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0030_alter_booking_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serial_number',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
