# Generated by Django 4.0.5 on 2023-02-23 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIBSYS', '0033_remove_issuebook_unique_addbook,unique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.addbook'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
