# Generated by Django 4.0.5 on 2023-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0034_alter_issuebook_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAcquisitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Acquired', 'Acquired')], default='Pending', max_length=30)),
            ],
        ),
    ]
