# Generated by Django 4.0.5 on 2023-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0035_bookacquisitionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookacquisitionrequest',
            name='requester',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
