# Generated by Django 4.0.5 on 2023-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0037_returnedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbook',
            name='return_date',
            field=models.DateField(auto_now=True),
        ),
    ]
