# Generated by Django 4.0.5 on 2023-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0038_alter_returnedbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbook',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
