# Generated by Django 4.0.5 on 2023-03-09 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIBSYS', '0040_alter_booking_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=150)),
                ('unit_name', models.CharField(max_length=150)),
                ('unit_code', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('type_of_exam', models.CharField(choices=[('Main exam', 'Main exam'), ('CAT', 'CAT')], default='Main exam', max_length=150)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
