# Generated by Django 4.0.5 on 2023-03-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0041_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_title',
        ),
    ]
