# Generated by Django 4.0.5 on 2023-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0042_remove_exam_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/%y'),
        ),
    ]
