# Generated by Django 4.0.5 on 2023-03-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0043_exam_exam_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbook',
            old_name='type',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='addbook',
            old_name='file',
            new_name='upload_ebook',
        ),
    ]
