# Generated by Django 4.0.5 on 2023-03-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0044_rename_type_addbook_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='clients_name',
        ),
        migrations.DeleteModel(
            name='BorrowBook',
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
