# Generated by Django 4.0.5 on 2023-03-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0046_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
