# Generated by Django 4.0.5 on 2023-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0047_fine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='over_due_by',
            field=models.IntegerField(default=10),
        ),
    ]
