# Generated by Django 4.0.5 on 2023-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0048_fine_over_due_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issuedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
