# Generated by Django 4.0.5 on 2023-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0049_alter_issuebook_issuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='copies_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
