# Generated by Django 4.0.5 on 2023-03-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0050_addbook_copies_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='copies_remaining',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
    ]
