# Generated by Django 4.0.5 on 2023-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0051_alter_addbook_copies_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='copies_remaining',
            field=models.IntegerField(default=1),
        ),
    ]
