# Generated by Django 4.0.5 on 2023-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0052_alter_addbook_copies_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbook',
            old_name='upload_ebook',
            new_name='ebook',
        ),
        migrations.AlterField(
            model_name='addbook',
            name='state',
            field=models.CharField(choices=[('ebook', 'online'), ('physical', 'physical'), ('physical/ebook', 'physical/online')], default='online', max_length=20),
        ),
    ]
