# Generated by Django 4.0.5 on 2023-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0053_rename_upload_ebook_addbook_ebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='state',
            field=models.CharField(choices=[('ebook', 'ebook'), ('physical', 'physical'), ('physical/ebook', 'physical/ebook')], default='online', max_length=20),
        ),
    ]
