# Generated by Django 4.0.5 on 2023-03-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0054_alter_addbook_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.addbook'),
        ),
    ]
