# Generated by Django 4.0.5 on 2023-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0055_alter_booking_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnedbook',
            old_name='serial_number',
            new_name='isbn',
        ),
    ]
