# Generated by Django 4.0.5 on 2023-03-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0056_rename_serial_number_returnedbook_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='serial_number',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='returnedbook',
            old_name='isbn',
            new_name='serial_number',
        ),
    ]
