# Generated by Django 4.0.5 on 2023-03-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0057_rename_serial_number_booking_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='serial_number',
            new_name='isbn',
        ),
    ]
