# Generated by Django 4.0.5 on 2023-03-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0060_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
    ]
