# Generated by Django 4.0.5 on 2023-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0062_rename_book_rating_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
