# Generated by Django 4.0.5 on 2023-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0064_addbook_co_authors_addbook_edition_addbook_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
