# Generated by Django 4.0.5 on 2023-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0065_addbook_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='year',
            field=models.CharField(default='2010', max_length=150),
        ),
    ]
