# Generated by Django 4.0.5 on 2023-03-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0066_alter_addbook_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='year',
        ),
    ]
