# Generated by Django 4.0.5 on 2023-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0067_remove_addbook_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
