# Generated by Django 4.0.5 on 2023-04-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0071_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='state',
            field=models.CharField(choices=[('ebook', 'ebook'), ('print', 'print'), ('physical/ebook', 'physical/ebook')], default='online', max_length=20),
        ),
    ]
