# Generated by Django 4.0.5 on 2023-04-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0072_alter_addbook_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='state',
            field=models.CharField(choices=[('ebook', 'ebook'), ('print', 'print'), ('print/ebook', 'print/ebook')], default='online', max_length=20),
        ),
    ]
