# Generated by Django 4.0.5 on 2023-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0073_alter_addbook_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
