# Generated by Django 4.0.5 on 2023-04-08 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0075_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
