# Generated by Django 4.0.5 on 2023-08-04 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0079_alter_fine_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=90)),
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 15, 0, 40, 27121)),
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('copies', models.IntegerField(default=1)),
                ('copies_remaining', models.IntegerField(default=1)),
                ('description', models.TextField(default=' ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/books/%y')),
                ('state', models.CharField(choices=[('ebook', 'ebook'), ('print', 'print'), ('print/ebook', 'print/ebook')], default='online', max_length=20)),
                ('genre', models.CharField(choices=[('Engineering', (('Civil Engineering', 'Civil Engineering'), ('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'))), ('Economics', ((' Classical economics', ' Classical economics'), ('Neo-classical economics', 'Neo-classical economics'))), ('Novel', 'Novel'), ('Science', 'Science'), ('Business', 'Business'), ('Mathematics', 'Mathematics')], default='Engineering', max_length=50)),
                ('ebook', models.FileField(blank=True, null=True, upload_to='books/%y')),
                ('pages', models.IntegerField()),
                ('edition', models.CharField(default='first edition', max_length=50)),
                ('publisher', models.CharField(default='Nami printers', max_length=150)),
                ('co_authors', models.CharField(blank=True, max_length=240, null=True)),
                ('year', models.CharField(max_length=150)),
                ('call_number', models.CharField(max_length=150)),
                ('ISBN', models.CharField(blank=True, max_length=150, null=True)),
                ('eISBN', models.CharField(blank=True, max_length=150, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.library'),
        ),
    ]
