# Generated by Django 4.0.5 on 2023-08-07 08:20

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0081_alter_fine_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='images/books/%y'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 11, 20, 16, 527611)),
        ),
    ]
