# Generated by Django 4.0.5 on 2023-08-10 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0082_alter_bookdetail_cover_image_alter_fine_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 15, 22, 11, 282814)),
        ),
    ]
