# Generated by Django 4.0.5 on 2023-08-14 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0083_alter_fine_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 10, 56, 48, 543782)),
        ),
        migrations.AlterField(
            model_name='history',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
    ]
