# Generated by Django 4.0.5 on 2023-08-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0085_remove_history_serial_number_history_book_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Announcement',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='book_issued',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fine',
            name='over_due_by',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fine',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fine',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
    ]
