# Generated by Django 4.0.5 on 2023-08-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0089_remove_history_book_detail_history_book_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='issuedate',
            new_name='issue_date',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='returnedbook',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='reviewed_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='LIBSYS.book'),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='book_issued',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
        migrations.AddField(
            model_name='rating',
            name='book_rated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='ebook',
            field=models.FileField(blank=True, help_text='Enter the path of the ebook here', null=True, upload_to='books/%y'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
    ]
