# Generated by Django 4.0.5 on 2023-08-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBSYS', '0090_rename_issuedate_issuebook_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedbook',
            name='returned_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LIBSYS.book'),
        ),
    ]
