# Generated by Django 4.0.5 on 2022-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic/default.jpg', null=True, upload_to='images/profile_pic/%y'),
        ),
    ]
